### ISSUE TITLE
ServerListener logs everything twice.

### ISSUE THREAD

**Issue by zack6849** [FoxDev/FoxBotNG#2]
![https://www.zack6849.com/uploads/2a8X4v0z2n5f494.png](https://www.zack6849.com/uploads/2a8X4v0z2n5f494.png)

Still happens, even with my plugin manager disabled, must be something wrong with the ServerListener.

**Comment by TheReverend403** [comment]
Fixed in 35151ebf5390a1f76c3bac35f0d147346423d2e4
